### ISSUE TITLE
Update ag-Grid to 23.x

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1597]
As always will want to carefully review changelog for the releases since our currently installed version. 

Note that we have some custom handling to support the notion of flex columns - this has now been added to the grid, and is something we should revisit.

Also note that we hope this update might clear us for the overall react update in #1312

**Comment by peterjcoffman** [comment]
The ag-Grid changelog can be found here:

https://www.ag-grid.com/ag-grid-changelog/

I have found a few things that may be problems for us:

1. 
```It is now possible to hide filters shown in the Filters Tool Panel by using 'ColDef.suppressFiltersToolPanel = true'.
'suppressToolPanel' has been replaced with 'suppressColumnsToolPanel' / 'suppressFiltersToolPanel'.```
We use `suppressToolPanel` in Column.js.
2.
```
Use of props.reactContainer to style the containing div element has been deprecated and will be removed in a future release.
```
We use `getReactContainerClasses` for styling in Column.js. I do not believe this is what the changelog is referring to, but I'd like to make sure.

None of the breaking changes seem to be relevant to us.

**Comment by lbwexler** [comment]
Hi:

Can we prioritize getting a P/R for this and getting this(and even the react upgrade as well) in to develop?

Malvina is here today to do some smoke testing, and I would like to make use of that....

**Comment by peterjcoffman** [comment]
Another issue: On the Toolbox News app, I see the following error on the console:

```
ag-Grid: React Component 'undefined' not created within 1000ms
```

I am not sure what is causing this. It does not occur on the other DataView examples. I have turned off the itemRenderer, LoadSupport, filtering, and the onRowDoubleClicked methods, but the problem persists.

**Comment by peterjcoffman** [comment]
Here is the PR:

https://github.com/xh/hoist-react/pull/1601

This PR upgrades the dependency and has a fix for the `suppressToolPanel` problem. The problem on the News app is not yet fixed.

**Comment by peterjcoffman** [comment]
I found something strange on the News app that may be related to the problem we are seeing. Here is a screenshot of the React dev tools:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/48924151/73277714-8dfa4b00-41b8-11ea-9493-bd6ea6ccb3f4.png">

[This person](https://github.com/ag-grid/ag-grid/issues/3222#issuecomment-568135480) had a similar problem and says it was caused by returning 'null' from some component. This is consistent with the fact that ag-Grid is complaining about an `undefined` component taking too long to create. Only one component shows up with no name in the dev tools, which I find suspicious.

**Comment by peterjcoffman** [comment]
The problem was with defaulting GridModel.emptyText to null. This would result in ag-Grid getting a noRowsOverlayComponentFramework of null, which would in turn trigger the error. I instead default the emptyText to an empty string, which solves the problem.

**Comment by amcclain** [comment]
Hi - seeing the following warning on the console when showing the default context menu - looks like we need to do a bit more here:

```
ag-Grid: unable to use Copy from Menu as module @ag-grid-enterprise/clipboard is not present. You need to load the module with: import "@ag-grid-enterprise/clipboard"

ag-Grid: unable to use Copy with Headers from Menu as module @ag-grid-enterprise/clipboard is not present. You need to load the module with: import "@ag-grid-enterprise/clipboard"
```

Will look around carefully for any other potential issues - we really want to bang on this one.

**Comment by peterjcoffman** [comment]
This is caused by this change:

https://www.ag-grid.com/javascript-grid-modules/

We can fix this by changing our package.json to
```
    "@ag-grid-community/all-modules": "~22.1.1",
    "@ag-grid-enterprise/all-modules": "~22.1.1",
```
Or we can import only the things we actually use, which should cut down on the size of the application.

**Comment by peterjcoffman** [comment]
This PR should fix the modules problem:

https://github.com/xh/hoist-react/pull/1612

**Comment by lbwexler** [comment]
Closing this again, but we should continue to test aggressively

**Comment by lbwexler** [comment]
REopening, this has been removed from the snapshot, due to issues with rendering custom react elements.  Will return in hoist 30.

**Comment by amcclain** [comment]
Updated to reflect recent ag-Grid 23.x release - I see they are now on 23.0.1.

@TomTirapani  and @lbwexler - could we recap any known issues and/or retest with the latest? Apologies, having a hard time keeping track / keeping up, but what were the issues noted above "rendering custom react elements"?  

The comments above from Jan 28 seem related, but also seem to indicate some subset of those issues were resolved (although I am not counting on anything here).

Thanks - would love to catch up again on our ag-grid major version.

**Comment by TomTirapani** [comment]
Will update the branch to 23.0.1 and see if I can get an understanding of what the outstanding issues are

**Comment by lbwexler** [comment]
Please see the comment in the PR to see what we are looking to be fixed:

https://github.com/xh/hoist-react/pull/1606

The flashing introduced for embedded react components here was the blocker

**Comment by lbwexler** [comment]
According to the ag-Grid changelog, the blocking issue: 

AG-3852 |   | 23.0.0 | react: cellRenderer being remounted when updating

is now fixed.

**Comment by TomTirapani** [comment]
Okay great, thanks for the link - will check it out and see if can still reproduce.

Playing around with v23 now. The theme changes don't seem too significant, had to make a couple of tweaks but since we're not using the SASS variables not too much needed to be changed. There are some slight difference (e.g. lighter text for headers) that we can review and see if we prefer.

Context Menus throw a bunch of errors, seemingly related to the new support for keyboard navigation.

**Comment by TomTirapani** [comment]
Updated the branch to use v23.

All looks good so far - can confirm AG-3852 seems to be resolved. I unwound our custom context menu keyboard navigation to use their built-on solution.

There have been some styling changes to use a lighter font for the grid headers. Honestly can't decide if this is an improvement or something we should seek to override. Happy to override with our standard font color, but wanted to check opinions on if this is an improvement or not:

v21:
<img width="535" alt="v21" src="https://user-images.githubusercontent.com/3017757/77446298-27736100-6de6-11ea-893d-f301287eb9d7.png">

v23:
<img width="536" alt="v23" src="https://user-images.githubusercontent.com/3017757/77446310-29d5bb00-6de6-11ea-87ab-f79ad4f87318.png">

**Comment by lbwexler** [comment]
I actually like that it is a bit more distinguished from the data.

**Comment by amcclain** [comment]
Yes I do as well - we are going even further in the client project I'm working on using our theme vars:

<img width="596" alt="Screen Shot 2020-03-24 at 6 18 27 PM" src="https://user-images.githubusercontent.com/225806/77482261-e9813780-6dfb-11ea-9cca-ad5721c68e82.png">

(Not suggesting we make this the default, just saying that I think some distinction can be useful.)

Looking @ the screenshot though - does it seem like our default headers are a few pixels too tall?

**Comment by TomTirapani** [comment]
Great, happy you guys like the distinctive headers, I feel the same way.

Good catch on the header height - will tweak in the branch

**Comment by TomTirapani** [comment]
Tweaked the header height by 1px - think it looks better now in all sizing modes
